# https://docs.getdbt.com/reference/warehouse-setups/bigquery-setup
# https://github.com/PrefectHQ/prefect-dbt/blob/main/prefect_dbt/cli/commands.py#L129

default:
    target: dev
    outputs:
        dev:
            dataset: thelook_ecommerce
            job_execution_timeout_seconds: 300
            job_retries: 1
            keyfile: the-data-strategist-5482b53309d2.json
            location: US
            method: service-account
            priority: interactive
            project: the-data-strategist
            threads: 1
            type: bigquery
